name: Django CI

on:
  push:
    branches: [ "main", "Greta" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 coveralls

      - name: Check code formatting with black
        run: python -m black --check .

      - name: Check flake8 linter
        run: python -m flake8 .

      - name: Run tests with coverage
        run: python -m coverage run --source=polls manage.py test polls

      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: python -m coveralls
